services:
  app:
    image: arungh/pets-api:latest
    container_name: pets_app
    depends_on:
      - db
    ports:
      - "8081:8081"
    env_file:
      - .env
    environment:
      DB_HOST: db          # override ONLY inside Docker
    volumes:
      - uploads_volume:/app/uploads
    networks:
      - pets_network

  db:
    image: postgres:15
    container_name: pets_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - pets_network

volumes:
  postgres_data:
  uploads_volume:

networks:
  pets_network:
